### ISSUE TITLE
Can't configure conditions

### ISSUE THREAD

**Issue by keyman500** [rezaies/moodle-profilefield_conditional#13]
I'm using moodle 3.11 and nothing happens when I click configure conditions

**Comment by hmb201** [comment]
Hi, I´m also having the same issue on Moodle 3.11
Is there any update on this? Thanks.

**Comment by CampusJustiz** [comment]
Same here...

**Comment by rezaies** [comment]
Thank you for reporting the issue.
This is fixed in the latest version.
