### ISSUE TITLE
Problems with CSV upload and DB sync

### ISSUE THREAD

**Issue by OT-AndreyUskov** [rezaies/moodle-profilefield_conditional#14]
There are problems with user upload via CSV file or external database.

Configure conditional field as follows.
![Conditions](https://user-images.githubusercontent.com/80508040/123285357-a2f61d80-d515-11eb-9745-688cc10406a2.png)

CSV file.
Even though you provide required values in CSV it says you must fill in the required field and you cannot leave it empty.
![Upload_preview](https://user-images.githubusercontent.com/80508040/123285392-ad181c00-d515-11eb-8de5-49c0240dd71a.png)

External database.
The value of the conditional field does not sync.
1. The conditional field set up to make another field required.
2. A user fills in the conditional field himself.
3. You fill in database but leave the required field empty.
4. You synchronize with the database.
5. Required profile field is empty in the users profile.
6. There is no error output and when the user logs in the system does not redirect him to the profile page to fill the required field in.

**Comment by jasimp** [comment]
i am having the same  issue and what i realized is we have to make separate list depends the conditional field value and remove that filed from the CSV file. While uploading you can select that conditional field value from the dropdown at the bottom of the upload window
i your case remove the below field from the csv and make separate list with option 1, option 2, and option 3 and while uploading select the conditional field value manually

![image](https://user-images.githubusercontent.com/7235269/126633437-da9c1174-86db-4aa5-baac-bc7b89028418.png)


hope the plug in creator will fix this issue soon

**Comment by rezaies** [comment]
This is fixed now. Field validation will be bypassed for bulk user uploads.
