### ISSUE TITLE
Doesn't work with latest version of Moodle

### ISSUE THREAD

**Issue by keyman500** [rezaies/moodle-profilefield_conditional#16]
I've tried to use this plugin on the latest version of Moodle but it doesn't work when you click on configure conditions nothing pops up the button does nothing.

**Comment by azmatksa** [comment]
We also tried on Moodle 3.11, the Configure conditions button is not working.

In console there is warnings **"There was an issue retrieving Bootstrap's version. Ensure Bootstrap is being loaded before bootstrap-select and there is no namespace collision. If loading Bootstrap asynchronously, the version may need to be manually specified via $.fn.selectpicker.Constructor.BootstrapVersion. TypeError: Cannot read properties of undefined (reading 'Constructor')"**



![image](https://user-images.githubusercontent.com/49816686/133254268-95ae4a27-decc-42ba-b94d-f02dfd68ee7c.png)

**Comment by rezaies** [comment]
Thank you for your report.
A new version is available.
Closing.
