### ISSUE TITLE
Current Master Branch throws javascript errors in Moodle version 3.10.11

### ISSUE THREAD

**Issue by JPHege** [rezaies/moodle-profilefield_conditional#19]
Current Master Branch throws “Uncaught ReferenceError: require is not defined” javascript errors in version Moodle 3.10.11 (Build: 20220509).  This prevents users from accessing the “Configure conditions” settings as pressing the button no longer brings up the conditions. 

https://github.com/rezaies/moodle-profilefield_conditional/commits/master 

*STEPS TO REPLICATE*
1.  Install latest master branch of plugin into Moodle 3.10.11
2.  Create a new “conditional field”, profile field or edit previously created one.
3.  In the “Specific Settings” section click on the “Configure conditions” box

OBSERVED BEHAVIOR:
The conditions do not open up.  This prevents any “Save Changes” from happening as the plugin requires the conditions to be configured.   When viewing the developer tools you can see the javascript error.  This issue effectively makes the plugin unusable in 3.10.11. 

![image](https://user-images.githubusercontent.com/107279963/173150434-317f5f5f-2ad4-42ea-8bc3-09610da0f3a0.png)

 
EXPECTED BEHAVIOR:
The “configure conditions” should open up normally and no javascript errors displaying in the Browser developer tools. 

*ADDITIONAL INVESTIGATION NOTES*
Tested Master Branch in 3.11.6+ (Build: 20220415), and issue not present.  Plugin works normally.  

Previous commit “466dba4 - Error Message Language Filter” does work in 3.10.11.  Issue only present after commit “a0e7bce - Make the plugin compatible with Moodle 3.11 onwards”

**Comment by rezaies** [comment]
Hi @JPHege 
The master branch only is compatible with Moodle 3.11 and onwards. For Moodle 3.10 you can still use the 310 branch.
