### ISSUE TITLE
Errors with Moodle 4.0.4+

### ISSUE THREAD

**Issue by sridgway1** [rezaies/moodle-profilefield_conditional#21]
We have been using conditional field plugin for some years with Moodle 3
we recently upgraded to 
4.0.4+ (Build: 20221007)
mariadb 10.3.35
php 10.3.35

We are getting the following errors reported with the Moodle bug tracker

Too much data passed as arguments to js_call_amd("profilefield_conditional/conditions", "apply"). Generally there are better ways to pass lots of data from PHP to JavaScript, for example via Ajax, data attributes, ... . This warning is triggered if the argument string becomes longer than 1024 characters.
- line 1066 of /lib/outputrequirementslib.php: call to debugging()
- line 115 of /user/profile/field/conditional/field.class.php: call to page_requirements_manager->js_call_amd()
- line 159 of /user/profile/lib.php: call to profile_field_conditional->edit_field_add()
- line 779 of /user/profile/lib.php: call to profile_field_base->edit_field()
- line 92 of /login/signup_form.php: call to profile_signup_fields()
- line 214 of /lib/formslib.php: call to login_signup_form->definition()
- line 317 of /lib/authlib.php: call to moodleform->__construct()
- line 80 of /login/signup.php: call to auth_plugin_base->signup_form()

Kind regards
Stephen

**Comment by rezaies** [comment]
This is fixed now.
