### ISSUE TITLE
Does not appear ready for PHP 8.0

### ISSUE THREAD

**Issue by goose2000** [rezaies/moodle-profilefield_conditional#25]
I a Moodle 4.0.6 site using profilefield_conditional but just found after upgrading to PHP 8.0+ there was this error on the registration form:

array_merge() does not accept unknown named parameters

![image001](https://user-images.githubusercontent.com/2395298/215617128-962730a1-75ec-4fed-a29e-4dad18cb82ee.png)

**Comment by rezaies** [comment]
Fixed.
