### ISSUE TITLE
Troubles to add a new field

### ISSUE THREAD

**Issue by eldenico** [rezaies/moodle-profilefield_conditional#4]
Hello, I guess it's a very good plugin, although I have a trouble. When I select the "Conditional Field" it redirects me to: "/user/profile/index.php?id=0&action=editfield&datatype=conditional"; and shows this error mesage: 

"
Esta página no funciona

La página no puede procesar esta solicitud ahora.
HTTP ERROR 500
"

I tried with a checkbox and the redirection is almost the same: /user/profile/index.php?id=0&action=editfield&datatype=checkbox".

Moodle Version 3.1
Language: Spanish

Following instructions from Shamim RezaieSun, on 30 Jul 2017, 3:53 AM at https://moodle.org/plugins/profilefield_conditional: 

Please turn on debugging mode in 'Site Administration > Development > Debugging'.
Set 'Debug messages' to 'DEVELOPER: extra Moodle debug messages for developers' and select the 'Display debug messages' checkbox. Then please try again to add a conditional field. You would see an error message with some useful information about the error.
Please file an issue at https://github.com/rezaies/moodle-profilefield_conditional/issues and post debugging information there.

I made it and the error message says: Fatal error: Can't use function return value in write context in /path/to/my/installation/user/profile/field/conditional/define.class.php on line 126. 

I don't have this trouble with any other type of field.

**Comment by eldenico** [comment]
Additional data:
PHP Version 5.4.16

**Comment by rezaies** [comment]
This is now fixed although it was only affecting PHP versions less than 5.5
