### ISSUE TITLE
Moodle 3.5

### ISSUE THREAD

**Issue by dcahail** [rezaies/moodle-profilefield_conditional#6]
We needed to upgrade to Moodle 3.5. However, we use this plugin on the signup page. Now only the Title for the additional options shows up. Can you help us upgrade this plugin?

**Comment by Lat91** [comment]
I think you may have fallen foul of a newly-introduced bug in 3.5 see this issue as we had the same thing when we moved to 3.5 

https://tracker.moodle.org/browse/MDL-62965

**Comment by michael-milette** [comment]
According to that ticket, the bug has been fixed. Anyone know if this is compatible with Moodle 3.7. We are upgrading next week and we could really use this plugin.

**Comment by rezaies** [comment]
A new version for the recent Moodle versions is relased
