### ISSUE TITLE
Is there a plan to update this plugin? 

### ISSUE THREAD

**Issue by ned-code** [rezaies/moodle-profilefield_conditional#8]
Hello and thanks for this useful plugin. I notice that the code hasn't been updated for the last 3 years. Are you planning to update any time soon?  Can I support this work by providing some funds? I'm sure many people would find this plugin useful.  Thanks.

**Comment by rezaies** [comment]
Thank you @ned-code for your comment.
Updating this plugin was always on my list, but with life coming in the way it's not easy.
Thank you for offering to support this plugin. You can buy me some coffees at https://ko-fi.com/A31043G
That surely keeps me awake to prepare a new version :)

**Comment by rezaies** [comment]
A new version is released for the recent Moodle versions.
